# Generated by Django 4.2.2 on 2024-09-04 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_book_user'),
        ('ReadingLists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('reading_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReadingLists.readinglist')),
            ],
        ),
    ]
