# Generated by Django 4.2.2 on 2024-09-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_book_user'),
        ('ReadingLists', '0002_readinglistentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='reading_lists', to='Books.book'),
        ),
    ]
